### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by mdblack98** [Cloaked9000/frnetlib#16]
After "cmake ."
[  2%] Building CXX object CMakeFiles/frnetlib.dir/src/WebFrame.cpp.o
In file included from /home/osboxes/mike/frnetlib/include/frnetlib/HttpRequest.h:11,
                 from /home/osboxes/mike/frnetlib/include/frnetlib/WebSocket.h:10,
                 from /home/osboxes/mike/frnetlib/src/WebFrame.cpp:6:
/home/osboxes/mike/frnetlib/include/frnetlib/Http.h:17:10: fatal error: gtest/gtest.h: No such file or directory
 #include <gtest/gtest.h>
          ^~~~~~~~~~~~~~~

**Comment by Cloaked9000** [comment]
Probably an ordering issue with CMake, will take a proper look later, but a short term solution might be to install gtest on your system, or pass "-DBUILD_TESTS=False" to remove it as a dependency. If you don't have mbedtls installed either (and don't need SSL), then you can pass "-DUSE_SSL=False" too.

**Comment by Cloaked9000** [comment]
Fixed in https://github.com/Cloaked9000/frnetlib/commit/69407a6ac59e8c78f217720fe1d61904c9f7dd97
