### ISSUE TITLE
How much C++11 is in this, actually?

### ISSUE THREAD

**Issue by IngwiePhoenix** [Cloaked9000/frnetlib#17]
I have been trying to find a proper, small, easily embeddable cross-platform networking library (quite a mouthful, I know) for a project that I am working on. Unfortunately, since I want to be as cross-platform as possible, I try to be ISO C++98 compliant; that way, more compilers are supported. This attempt might be foolish in 2020, but you never know. :)

Anyway, since the README mentions that C++11 is required, I wanted to know "how much" C++11 is in there and if it would, in theory, be possible to backport it to C++98?

Kind regards,
Ingwie

**Comment by Cloaked9000** [comment]
Sorry for the late response, I keep spotting this, making a mental note to reply and then promptly forgetting. It's mostly template stuff in `fr::Packet` off the top of my head. Though there's also little bits and bobs around the project, and that's excluding dependencies like mbedtls if you want TLS. So it's probably quite a lot of work.
