### ISSUE TITLE
the header name shall be lowercase, "connection" instead of "Connection", because all header are added lowercase

### ISSUE THREAD

**Issue by ismart-omari** [Cloaked9000/frnetlib#20]
https://github.com/Cloaked9000/frnetlib/blob/7b4074dab2ddc2f4ceabb0303c4f2fad5f0e975a/src/HttpRequest.cpp#L146

i am playing with websocket client, and i spend hours to figure out that the header "connection" is duplicated

"connection" : "upgrade"
"Connection" : "keep-alive"

regards,
Omari

**Comment by Cloaked9000** [comment]
I've merged your PR to fix this thank you, I'll have a look at better case handling of headers though...
