### ISSUE TITLE
Build in windows.

### ISSUE THREAD

**Issue by MiaoDX** [Cloaked9000/frnetlib#6]
Hei, it seems that you are making a tiny and neat library and it should be `cross-platform` since there are so many platform specific codes, I am looking for a small lib with cross-platform ability and your example code seems appealing, but I failed to build in windows10 with vs2015. 😢 , there are tons of mistakes.

``` vi
cl : Command line warning D9002: ignoring unknown option '-m64',
``` 
it seems that `-m64 -fPIC  -pthread -lmbedtls -lmbedx509 -lmbedcrypto` are for linux, but they are just warnning.

``` vi
error C2556: 'float htonf(float)': overloaded function differs only by return type from 'unsigned int htonf(float)'
```

``` vi
error C2371: 'htonf': redefinition; different basic types
```

``` vi
[...]
[many many similar errors]
[...]
```

``` vi
frnetlib\src\SSLSocket.cpp(7): fatal error C1083: Cannot open include file: 'mbedtls/net_sockets.h': No such file or directory
```

And the wrong messages is just too much, the first one I can understand, but I did not choose `ssl` at the very beginning, so why still need them? And the others just make me dizzy.

So, 
1.have you build on windows, or am I missing something important? Hope will have a doc tell about how to build.
2.Can I choose not to compile ssl at all? (I am not so into cmake, so is it possible?)

Thanks for your time.

**Comment by Cloaked9000** [comment]
Ah, sorry. I've been using MinGW, the GCC port for my Windows builds, and there's a lot of little differences between the compilers.

The htonf() error for example, is because Visual C++ provides that function as standard, whereas it's not a standard POSIX function.

I'll have a look at fixing any compatability issues, and building it with Visual C++ later today, it shouldn't be too much work, I'll update this issue with an ETA once I've had a look. Thanks for your interest :)

**Comment by MiaoDX** [comment]
It would be great and great help for me, thanks, but take your time please. (^_^)

Good Luck & Have Fun.

在2017年05月29日 00:19，Fred Nicolson<mailto:notifications@github.com> 写道：

Ah, sorry. I've been using MinGW, the GCC port for my Windows builds, and there's a lot of little differences between the compilers.

The htonf() error for example, is because Visual C++ provides that function as standard, whereas it's not a standard POSIX function.

I'll have a look at fixing any compatability issues, and building it with Visual C++ later today, it shouldn't be too much work, I'll update this issue with an ETA once I've had a look. Thanks for your interest :)

**Comment by Cloaked9000** [comment]
Hey, I've fixed the build errors, it was just a case of switching ssize_t's to int32_t's, and putting the network conversion code in ifdefs. However there are still build warnings which need to be fixed. Could you confirm that this builds properly and works for you?

**Comment by MiaoDX** [comment]
Thanks, it can be built successfully and the `main.cpp` runs with no problem, I will try other examples.
