### ISSUE TITLE
Some cross-platform build issues and suggestions.

### ISSUE THREAD

**Issue by MiaoDX** [Cloaked9000/frnetlib#9]
It does look nicer and more organized, however,

* I failed to build on win10+vs2015, especially the `googletest` part. But this time really no hurry, the demo example is enough for me right now.
* Even on ubuntu14.05, I need to hand remove `-lmbedtls -lmbedx509 -lmbedcrypto` in `CMAKE_CXX_FLAGS` since I do not want to use the `SSL` function.
* I think it makes things easier that the `examples` separated with main codebase so that people can just extract out the examples and do their own stuff. (Could we meet both ends, say, standalone and complete `CMakeLists.txt` but still can be used for the test?)

Regards,

--MiaoDX

**Comment by Cloaked9000** [comment]
Thanks for the heads up, I didn't get time to fully test it last night. Does it fail to build even if you disable testing, with the BUILD_TESTS flag in Cmake? 

Edit: Also, why keep the examples separate, you can already choose to enable or disable them with CMake flags?

**Comment by Cloaked9000** [comment]
I've made some changes, so it should build smoothly. But I've had to disable by default the examples and tests on Windows as there's linking issues, so I'll need to figure out what's wrong before re-enabling.

**Comment by MiaoDX** [comment]
Yeap, and sorry for the late reply, it does exist some cross-platform problems but you can not build Rome in a day. 😺

**Comment by Cloaked9000** [comment]
I've spent some time getting the tests and examples building properly on Windows with MSVC, and they should work fine now.

Interestingly though, the tests fail on MSVC. The fr::Packet packing, with floats seems to be broken:

`[ RUN      ] PacketTest.pack_and_unpack_ints
C:\Users\Administrator\Desktop\frnetlib-master\tests\PacketTest.cpp(20): error:
      Expected: b1
      Which is: 11.52
To be equal to: b2
      Which is: 5.17218e-39

[  FAILED  ] PacketTest.pack_and_unpack_ints (1 ms)`

So it looks like a little bit of work is needed there.

Edit: Newest commit fixes this, it disables MSVC's inbuilt network conversion functions and the tests pass fine.
